const ACTIONS = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  SIGNIN_REQUEST: "SIGNIN_REQUEST",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "SIGNIN_FAILURE",
  POST_ADD_REQUEST: "POST_ADD_REQUEST",
  POST_ADD_SUCCESS: "POST_ADD_SUCCESS",
  POST_ADD_FAILURE: "POST_ADD_FAILURE",
  THEME_DARK: "THEME_DARK",
  THEME_LIGHT: "THEME_LIGHT",
  NETWORK_ERR: "NETWORK_ERR",
  DEL_POST_REQ:"DEL_POST_REQ",
  DEL_POST_SUCC:"DEL_POST_SUCC",
  DEL_POST_FAIL:"DEL_POST_FAIL",
  DEL_POST_ID:"DEL_POST_ID",
  DEL_POST_OFF:"DEL_POST_OFF"
};

export default ACTIONS;
